version: '3.9'

services:
    node:
        user: node
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: ${NODE_ENV}
        volumes:
            - ./:/home/node/app
            - node_modules:/home/node/app/node_modules
        tty: true
        command: npm start

volumes:
    node_modules:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./node_modules
