version: '3.9'

services:
    node:
        user: node
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: ${NODE_ENV}
        volumes:
            - ./:/home/node/app
            - node_modules:/home/node/app/node_modules
        tty: true
        command: yarn start
        networks:
            default:
                ipv4_address: 172.18.0.2

volumes:
    node_modules:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./node_modules

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                -
                    subnet: 172.18.0.0/24
                    gateway: 172.18.0.1